import { getPublicJwk } from "./jwt";


/**
 * Handler for /.well-known/jwks.json
 * Returns a JSON object with a single property "keys" containing an array of JWKs.
 * The array will contain a single JWK which is the public key of the server.
 * This is used for verifying the signature of JWTs generated by the server.
 */
export function jwksHandler(_req: any, res: any) {
    res.json({ keys: [getPublicJwk()] });
}